name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: cd src/spriamentum2 && pub get
    - name: Run tests
      run: cd src/spriamentum2 && pub run test
